# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoctorCell' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoctorCell
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'RxDataSources'
  pod 'Action'
  pod 'Firebase/Core'

  target 'DoctorCellTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
